<?php

namespace ContainerGIUxLaH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1kHCIjGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1kHCIjG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1kHCIjG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'borrowedbook' => ['privates', '.errored..service_locator.1kHCIjG.App\\Entity\\Borrowedbook', NULL, 'Cannot autowire service ".service_locator.1kHCIjG": it needs an instance of "App\\Entity\\Borrowedbook" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'borrowedbook' => 'App\\Entity\\Borrowedbook',
            'entityManager' => '?',
        ]);
    }
}
