<?php

namespace ContainerGIUxLaH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8_AdlFpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8.adlFp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8.adlFp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'hasherInterface' => ['privates', '.errored.4j.hDhz', NULL, 'Cannot determine controller argument for "App\\Controller\\UserProfileController::changePasswordProfile()": the $hasherInterface argument is type-hinted with the non-existent class or interface: "App\\Controller\\PasswordHasherInterface". Did you forget to add a use statement?'],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
        ], [
            'entityManager' => '?',
            'hasherInterface' => '?',
            'passwordHasher' => '?',
        ]);
    }
}
