<?php

namespace ContainerGIUxLaH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_4j_HDhzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.4j.hDhz' shared service.
     *
     * @return \App\Controller\PasswordHasherInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\UserProfileController::changePasswordProfile()": the $hasherInterface argument is type-hinted with the non-existent class or interface: "App\\Controller\\PasswordHasherInterface". Did you forget to add a use statement?');
    }
}
