<?php

namespace ContainerGIUxLaH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q9mcs9pService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.q9mcs9p' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.q9mcs9p'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'borrowedbook' => ['privates', '.errored..service_locator.q9mcs9p.App\\Entity\\Borrowedbook', NULL, 'Cannot autowire service ".service_locator.q9mcs9p": it needs an instance of "App\\Entity\\Borrowedbook" but this type has been excluded in "config/services.yaml".'],
        ], [
            'borrowedbook' => 'App\\Entity\\Borrowedbook',
        ]);
    }
}
