<?php

namespace ContainerGIUxLaH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Rj397iKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rj397iK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rj397iK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\ApiBookController::list' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\BookController::delete' => ['privates', '.service_locator.FaIXBcg', 'get_ServiceLocator_FaIXBcgService', true],
            'App\\Controller\\BookController::edit' => ['privates', '.service_locator.FaIXBcg', 'get_ServiceLocator_FaIXBcgService', true],
            'App\\Controller\\BookController::index' => ['privates', '.service_locator.mECLSgp', 'get_ServiceLocator_MECLSgpService', true],
            'App\\Controller\\BookController::new' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\BorrowedbookController::borrowerBooks' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\BorrowedbookController::delete' => ['privates', '.service_locator.1kHCIjG', 'get_ServiceLocator_1kHCIjGService', true],
            'App\\Controller\\BorrowedbookController::edit' => ['privates', '.service_locator.1kHCIjG', 'get_ServiceLocator_1kHCIjGService', true],
            'App\\Controller\\BorrowedbookController::index' => ['privates', '.service_locator.q1cMIug', 'get_ServiceLocator_Q1cMIugService', true],
            'App\\Controller\\BorrowedbookController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\BorrowedbookController::returnBook' => ['privates', '.service_locator.1kHCIjG', 'get_ServiceLocator_1kHCIjGService', true],
            'App\\Controller\\BorrowedbookController::show' => ['privates', '.service_locator.q9mcs9p', 'get_ServiceLocator_Q9mcs9pService', true],
            'App\\Controller\\OgrenciController::index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\RaporController::mostReaders' => ['privates', '.service_locator.PqFlX29', 'get_ServiceLocator_PqFlX29Service', true],
            'App\\Controller\\RaporController::reports' => ['privates', '.service_locator.gheOYaX', 'get_ServiceLocator_GheOYaXService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.V6D1oJY', 'get_ServiceLocator_V6D1oJYService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\UserProfileController::changePasswordProfile' => ['privates', '.service_locator.8.adlFp', 'get_ServiceLocator_8_AdlFpService', true],
            'App\\Controller\\UserProfileController::edit' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ApiBookController:list' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\BookController:delete' => ['privates', '.service_locator.FaIXBcg', 'get_ServiceLocator_FaIXBcgService', true],
            'App\\Controller\\BookController:edit' => ['privates', '.service_locator.FaIXBcg', 'get_ServiceLocator_FaIXBcgService', true],
            'App\\Controller\\BookController:index' => ['privates', '.service_locator.mECLSgp', 'get_ServiceLocator_MECLSgpService', true],
            'App\\Controller\\BookController:new' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\BorrowedbookController:borrowerBooks' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\BorrowedbookController:delete' => ['privates', '.service_locator.1kHCIjG', 'get_ServiceLocator_1kHCIjGService', true],
            'App\\Controller\\BorrowedbookController:edit' => ['privates', '.service_locator.1kHCIjG', 'get_ServiceLocator_1kHCIjGService', true],
            'App\\Controller\\BorrowedbookController:index' => ['privates', '.service_locator.q1cMIug', 'get_ServiceLocator_Q1cMIugService', true],
            'App\\Controller\\BorrowedbookController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\BorrowedbookController:returnBook' => ['privates', '.service_locator.1kHCIjG', 'get_ServiceLocator_1kHCIjGService', true],
            'App\\Controller\\BorrowedbookController:show' => ['privates', '.service_locator.q9mcs9p', 'get_ServiceLocator_Q9mcs9pService', true],
            'App\\Controller\\OgrenciController:index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\RaporController:mostReaders' => ['privates', '.service_locator.PqFlX29', 'get_ServiceLocator_PqFlX29Service', true],
            'App\\Controller\\RaporController:reports' => ['privates', '.service_locator.gheOYaX', 'get_ServiceLocator_GheOYaXService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.V6D1oJY', 'get_ServiceLocator_V6D1oJYService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\UserProfileController:changePasswordProfile' => ['privates', '.service_locator.8.adlFp', 'get_ServiceLocator_8_AdlFpService', true],
            'App\\Controller\\UserProfileController:edit' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ApiBookController::list' => '?',
            'App\\Controller\\BookController::delete' => '?',
            'App\\Controller\\BookController::edit' => '?',
            'App\\Controller\\BookController::index' => '?',
            'App\\Controller\\BookController::new' => '?',
            'App\\Controller\\BorrowedbookController::borrowerBooks' => '?',
            'App\\Controller\\BorrowedbookController::delete' => '?',
            'App\\Controller\\BorrowedbookController::edit' => '?',
            'App\\Controller\\BorrowedbookController::index' => '?',
            'App\\Controller\\BorrowedbookController::new' => '?',
            'App\\Controller\\BorrowedbookController::returnBook' => '?',
            'App\\Controller\\BorrowedbookController::show' => '?',
            'App\\Controller\\OgrenciController::index' => '?',
            'App\\Controller\\RaporController::mostReaders' => '?',
            'App\\Controller\\RaporController::reports' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserProfileController::changePasswordProfile' => '?',
            'App\\Controller\\UserProfileController::edit' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ApiBookController:list' => '?',
            'App\\Controller\\BookController:delete' => '?',
            'App\\Controller\\BookController:edit' => '?',
            'App\\Controller\\BookController:index' => '?',
            'App\\Controller\\BookController:new' => '?',
            'App\\Controller\\BorrowedbookController:borrowerBooks' => '?',
            'App\\Controller\\BorrowedbookController:delete' => '?',
            'App\\Controller\\BorrowedbookController:edit' => '?',
            'App\\Controller\\BorrowedbookController:index' => '?',
            'App\\Controller\\BorrowedbookController:new' => '?',
            'App\\Controller\\BorrowedbookController:returnBook' => '?',
            'App\\Controller\\BorrowedbookController:show' => '?',
            'App\\Controller\\OgrenciController:index' => '?',
            'App\\Controller\\RaporController:mostReaders' => '?',
            'App\\Controller\\RaporController:reports' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserProfileController:changePasswordProfile' => '?',
            'App\\Controller\\UserProfileController:edit' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
