<?php

namespace ContainerGIUxLaH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBorrowedbookService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.1kHCIjG.App\Entity\Borrowedbook' shared service.
     *
     * @return \App\Entity\Borrowedbook
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.1kHCIjG": it needs an instance of "App\\Entity\\Borrowedbook" but this type has been excluded in "config/services.yaml".');
    }
}
